### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [RobertCsordas/MobilECG-II#1]
I would like to point out that identifiers like "[`_ECG_FILTERS_H`](https://github.com/xdever/MobilECG-II/blob/47def78b2a452c8689ce3d3feef63eab0f1b154a/Software/Common/SignalConditioning/EcgFilters.hpp#L1)" and "[`_PACKET_READER_HPP`](https://github.com/xdever/MobilECG-II/blob/e49f0e994a69fcc40fa01fd04349d958a04cac72/Software/Common/DataFormat/PacketReader.hpp#L21)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by RobertCsordas** [comment]
Thank you for reporting the issue! Fixed it in our part of the code. We leave third party libraries unchanged for easy updating in the future.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/xdever/MobilECG-II/commit/9960984c37f3b2f6d1e677e0ecacc5f91de0f59a).

Do any more source code places [need another look](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797)?

**Comment by RobertCsordas** [comment]
Feel free to look at the code and report it if there is an issue somewhere. You can also fork the code, fix the critical parts and create a pull request for it. Keep in mind however that there are lots of open source libs in the code: the whole STM32 folder in the firmware, Bluetopia, SCMRTOS, libeeprom, etc. We want to make the absolute minimum changes to these in order to be able to change or update them easily.

**Comment by elfring** [comment]
Would you like to report this issue also to the mentioned third party libraries if they are similarly affected?

How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?
