### ISSUE TITLE
Firmware Bluetopia compiling

### ISSUE THREAD

**Issue by rwoloszyn** [RobertCsordas/MobilECG-II#2]
Hi,
I found that in your firmware for ECG device you are using gcc precompilled 
bluetopia library (*.a file). Did you make any special configuraiton in your enviroment or you just added it as static library. I am fighting with this library and its file. I started Keil wrining in keil and its working but for pure gcc (for arm cross compiling) I cannot compile this library.

**Comment by RobertCsordas** [comment]
Hi,
No, it should compile just with the provided makefile. I used gcc 4.9.x when compiling.

**Comment by rwoloszyn** [comment]
@xdever  thanks. I am having many problems with it. When compiling with uVision Keil it worked 
straight away. Anyway thanks I will fight with it.
