### ISSUE TITLE
CardECG Component Value Clarifications?

### ISSUE THREAD

**Issue by KermMartian** [RobertCsordas/MobilECG-II#3]
I've been exploring a graphing calculator-powered ECG to show off at a local Maker Faire, and thus I was looking over the CardECG schematic. Could you please clarify the component specs of the diodes (D2, D3, D4, D5), the value of capacitor C2 attached to the uC's DAC0 and ADC1 pins, and the value (if any) of U6/U7 (DNP)? Thanks in advance.

**Comment by RobertCsordas** [comment]
The design had known bugs besides the missing values. I updated it to the most recent version.

**Comment by KermMartian** [comment]
Thanks so much for the update! For the curious hitting this same issue, although the commit is not contemporary with this issue, 063f45a does the trick.

**Comment by RobertCsordas** [comment]
I pushed another update. Please check it out.

**Comment by KermMartian** [comment]
Thanks again for that. And from examining the code, it appears that ADC1 is not actually used (and that DAC0 is always used at full voltage). Is that correct?

**Comment by KermMartian** [comment]
_bump_ Just checking to make sure I didn't misunderstand the currently-committed code. Apologies for the double message.
